language: node_js
arch:
 - amd64
 - ppc64le
node_js:  
  - 0.10
  - 14.0
  - 15.0
  # dropped unsupport node versions on power arch
jobs: 
  exclude:
    - arch: ppc64le
      node_js: "0.10"

before_script:
  - node tests/server.js &
  - sleep 1

script: phantomjs tests/runner.js

after_script:
  - kill -9 `cat tests/pid.txt`
  - rm tests/pid.txt
